version: '3.8'

services:

  mongodb:
    image: mongo
    container_name: netflix-mongo
    ports:
      - "27017:27017"

  backend:
    build: ./server
    container_name: netflix-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/netflix

  frontend:
    build: .
    container_name: netflix-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
